services:
  - type: web
    name: camera-control-system
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 main.py  # Используйте python3 вместо python
    plan: free
